### ISSUE TITLE
Callout does not work

### ISSUE THREAD

**Issue by BirkhoffG** [airtai/nbdev-mkdocs#173]
Just found this really nice project!!! I am considering switching to `nbdev-mkdocs` for hosting my documentations.

I found callout is not working when following the nbdev's notations. 

For example, when specifying the callout as suggested [here](https://nbdev.fast.ai/tutorials/qmd_intro.html#callouts),

```
::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `warning`, `important`, `tip`, and `caution`.
:::
```

It does not render correctly for `nbdev-mkdocs`.

**Comment by harishmohanraj** [comment]
Hi @BirkhoffG,

Thank you for your positive feedback on `nbdev-mkdocs`. It's great to hear that you're interested in using it to host your documentation.

We've added the issue to our development sprint and plan to fix it in the next release. We appreciate your patience as we work on this.

If you have any other questions or concerns, please don't hesitate to reach out. We're always here to help.

**Comment by davorrunje** [comment]
@BirkhoffG we just made a new release fixing callouts:

https://github.com/airtai/nbdev-mkdocs/releases/tag/0.4.0

We'll fix the other reported issues as well, please let us know how this one works for you and if you have any more requests/suggestions.
