### ISSUE TITLE
`sidebar.yml` gets overridden every `nbdev_mkdocs preview`

### ISSUE THREAD

**Issue by BirkhoffG** [airtai/nbdev-mkdocs#174]
`sidebar.yml` under the directory `nbs` gets overridden every `nbdev_mkdocs preview`.

I cannot manually specify my sidebar.

Reference: https://github.com/BirkhoffG/jax-dataloader/pull/15/commits/0030b35a80ba87d21f429fc46147be727ce61b7e

**Comment by harishmohanraj** [comment]
Hi @BirkhoffG 

Please try setting `custom_sidebar = True` in the `settings.ini` file and running the `nbdev_mkdocs preview` command. This will prevent `sidebar.yml` from being regenerated each time you rebuild your docs.

By default, nbdev generates the `sidebar.yml` file based on the directory structure of your source files during each doc build. However, if you wish to create a customized navigation sidebar, you must set `custom_sidebar = true` in your `settings.ini` file.

You can find more information on this in the nbdev documentation here: https://nbdev.fast.ai/explanations/docs.html#customizing-the-sidebar

**Comment by BirkhoffG** [comment]
Thanks @harishmohanraj
